CREATE TABLE CLIENTS
(
CLIENT_ID NUMBER(4)   NOT NULL,
CLIENT_NAME VARCHAR2(50),
MOBILE VARCHAR2(50),
ADDRESS VARCHAR2(100),
NID VARCHAR2(100),

CONSTRAINT CLIENT_PK PRIMARY KEY(CLIENT_ID)
);

CREATE TABLE CONTRACTS
(
CONTRACT_ID NUMBER(6)   NOT NULL,
CONTRACT_STARTDATE DATE,
CONTRACT_ENDDATE DATE,
PAYMENTS_INSTALLMENTS_NO NUMBER(6),
CONTRACT_TOTAL_FEES NUMBER(10,2),
CONTRACT_DEPOSIT_FEES NUMBER(10,2),
CLIENT_ID NUMBER(6),
CONTRACT_PAYMENT_TYPE VARCHAR2(250),
NOTES VARCHAR2(4000),

CONSTRAINT CONTRACT_PK PRIMARY KEY(CONTRACT_ID),
CONSTRAINT CLIENT_FK FOREIGN KEY(CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE INSTALLMENTS_PAID
(
INSTALLMENT_ID NUMBER   NOT NULL,
CONTRACT_ID NUMBER,
INSTALLMENT_DATE DATE,
INSTALLMENT_AMOUNT NUMBER(10,2),
PAID NUMBER(1),

CONSTRAINT INSTALL_PK PRIMARY KEY(INSTALLMENT_ID),
CONSTRAINT CONTRACT_FK FOREIGN KEY(CONTRACT_ID) REFERENCES CONTRACTS(CONTRACT_ID)
);