INSERT INTO CLIENTS (ADDRESS, CLIENT_NAME) VALUES ('CAIRO','CLIENT 1');
INSERT INTO CLIENTS (ADDRESS, CLIENT_NAME) VALUES ('ALEX','CLIENT 2');
INSERT INTO CLIENTS (ADDRESS, CLIENT_NAME) VALUES ('CAIRO','CLIENT 3');
INSERT INTO CLIENTS (ADDRESS, CLIENT_NAME) VALUES ('CAIRO','CLIENT 4');

INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES) 
VALUES (1, NULL, TO_DATE('01.01.2021','dd.mm.yyyy'), 'ANNUAL', TO_DATE('01.01.2023','dd.mm.yyyy'), 500000);
INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES) 
VALUES (2, 10000, TO_DATE('01.03.2021','dd.mm.yyyy'), 'QUARTER', TO_DATE('01.03.2024','dd.mm.yyyy'), 600000);
INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES) 
VALUES (3, 50000, TO_DATE('01.05.2021','dd.mm.yyyy'), 'QUARTER', TO_DATE('01.05.2023','dd.mm.yyyy'), 400000);
INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES)  
VALUES (4, NULL, TO_DATE('01.03.2021','dd.mm.yyyy'), 'MONTHLY', TO_DATE('01.03.2024','dd.mm.yyyy'), 700000);
INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES)  
VALUES (1, 300000, TO_DATE('01.04.2021','dd.mm.yyyy'), 'ANNUAL', TO_DATE('01.04.2026','dd.mm.yyyy'), 900000);
INSERT INTO CONTRACTS (CLIENT_ID, CONTRACT_DEPOSIT_FEES, CONTRACT_STARTDATE, CONTRACT_PAYMENT_TYPE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES) 
VALUES (3, 200000, TO_DATE('01.01.2021','dd.mm.yyyy'), 'HALF_ANNUAL', TO_DATE('01.01.2026','dd.mm.yyyy'), 1000000);
